version: '3.3'

volumes:
  mysql:
  uploads:
  plugins:
  themes:

services:
  db: 
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - themes:/var/www/html/wp-content/themes
      - plugins:/var/www/html/wp-content/plugins
      - uploads:/var/www/html/wp-content/uploads
    ports:
      - "8008:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress